# Generated by Django 3.0.8 on 2020-07-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='contact_date',
        ),
    ]
